language: dita
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - DITAMAP=dita/flowers/flowers.ditamap
  - DITAVAL=dita/pdf.ditaval
  - ANT_OPTS=-Xmx1024M
  - OUT_DIR=output
  - TEMP_DIR=temp
before_install:
- chmod +x .travis/publish.sh
